version: "3.8"

volumes:
  psql_ar_data:

services:
  ar-web:
    build:
      dockerfile: .build/Dockerfile
      context: .
    restart: unless-stopped
    image: ali_ar:dev
    volumes:
      - ./:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - ar-db
    command: bash -c 'while !</dev/tcp/ar-db/5432; do sleep 1; done; uvicorn app:app --host 0.0.0.0 --reload'

  ar-db:
    restart: unless-stopped
    image: postgres:14-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      postgres -c listen_addresses='*'

    volumes:
      - psql_ar_data:/var/lib/postgresql/data:z
    ports:
      - "5433:5432"
