version: "3.8"

volumes:
  psql_data:

services:
  web:
    build:
      dockerfile: .build/Dockerfile
      context: .
    restart: unless-stopped
    image: fastapi-piccolo:dev
    volumes:
      - ./:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python main.py'

  db:
    restart: unless-stopped
    image: postgres:14-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      postgres -c listen_addresses='*'

    volumes:
      - psql_data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
